---
abstract: 'ESLIF is Extended ScanLess InterFace'
author:
  - 'Jean-Damien Durand <jeandamiendurand@free.fr>'
build_requires:
  Carp: '0'
  Data::Dumper: '0'
  Encode: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Log::Any: '0'
  Log::Any::Adapter: '0'
  Math::BigFloat: '0'
  Math::BigInt: '0'
  POSIX: '0'
  Pod::Coverage::TrustPod: '0'
  Safe::Isa: '0'
  Test::CPAN::Changes: '0'
  Test::CPAN::Meta: '0'
  Test::CPAN::Meta::JSON: '0'
  Test::Deep: '1.128'
  Test::Deep::NoTest: '0'
  Test::Kwalitee: '0'
  Test::MinimumVersion: '0'
  Test::Mojibake: '0'
  Test::More: '1.3'
  Test::More::UTF8: '0'
  Test::NoTabs: '0'
  Test::Perl::Critic: '0'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
  Test::Portability::Files: '0'
  Test::Synopsis: '0'
  Test::Version: '0'
  Try::Tiny: '0'
  diagnostics: '0'
  open: '0'
  perl: '5.010'
  threads: '0'
  threads::shared: '0'
  utf8: '0'
configure_requires:
  Config::AutoConf: '0'
  Cwd: '0'
  ExtUtils::CBuilder: '0.280224'
  ExtUtils::Constant: '0'
  ExtUtils::MakeMaker: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
  File::Which: '0'
  File::chdir: '0'
  Perl::OSType: '0'
  Probe::Perl: '0'
  Try::Tiny: '0'
  perl: '5.006'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.031, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MarpaX-ESLIF
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
provides:
  MarpaX::ESLIF:
    file: lib/MarpaX/ESLIF.pm
    version: v6.0.33
  MarpaX::ESLIF::Base:
    file: lib/MarpaX/ESLIF/Base.pm
    version: v6.0.33
  MarpaX::ESLIF::Event::Type:
    file: lib/MarpaX/ESLIF/Event/Type.pm
    version: v6.0.33
  MarpaX::ESLIF::Grammar:
    file: lib/MarpaX/ESLIF/Grammar.pm
    version: v6.0.33
  MarpaX::ESLIF::Grammar::Properties:
    file: lib/MarpaX/ESLIF/Grammar/Properties.pm
    version: v6.0.33
  MarpaX::ESLIF::Grammar::Rule::Properties:
    file: lib/MarpaX/ESLIF/Grammar/Rule/Properties.pm
    version: v6.0.33
  MarpaX::ESLIF::Grammar::Symbol::Properties:
    file: lib/MarpaX/ESLIF/Grammar/Symbol/Properties.pm
    version: v6.0.33
  MarpaX::ESLIF::JSON:
    file: lib/MarpaX/ESLIF/JSON.pm
    version: v6.0.33
  MarpaX::ESLIF::JSON::Decoder:
    file: lib/MarpaX/ESLIF/JSON/Decoder.pm
    version: v6.0.33
  MarpaX::ESLIF::JSON::Decoder::RecognizerInterface:
    file: lib/MarpaX/ESLIF/JSON/Decoder/RecognizerInterface.pm
    version: v6.0.33
  MarpaX::ESLIF::JSON::Encoder:
    file: lib/MarpaX/ESLIF/JSON/Encoder.pm
    version: v6.0.33
  MarpaX::ESLIF::Logger::Level:
    file: lib/MarpaX/ESLIF/Logger/Level.pm
    version: v6.0.33
  MarpaX::ESLIF::Recognizer:
    file: lib/MarpaX/ESLIF/Recognizer.pm
    version: v6.0.33
  MarpaX::ESLIF::RegexCallout:
    file: lib/MarpaX/ESLIF/RegexCallout.pm
    version: v6.0.33
  MarpaX::ESLIF::Rule::PropertyBitSet:
    file: lib/MarpaX/ESLIF/Rule/PropertyBitSet.pm
    version: v6.0.33
  MarpaX::ESLIF::String:
    file: lib/MarpaX/ESLIF/String.pm
    version: v6.0.33
  MarpaX::ESLIF::Symbol:
    file: lib/MarpaX/ESLIF/Symbol.pm
    version: v6.0.33
  MarpaX::ESLIF::Symbol::EventBitSet:
    file: lib/MarpaX/ESLIF/Symbol/EventBitSet.pm
    version: v6.0.33
  MarpaX::ESLIF::Symbol::PropertyBitSet:
    file: lib/MarpaX/ESLIF/Symbol/PropertyBitSet.pm
    version: v6.0.33
  MarpaX::ESLIF::Symbol::Type:
    file: lib/MarpaX/ESLIF/Symbol/Type.pm
    version: v6.0.33
  MarpaX::ESLIF::Value:
    file: lib/MarpaX/ESLIF/Value.pm
    version: v6.0.33
  MarpaX::ESLIF::Value::Type:
    file: lib/MarpaX/ESLIF/Value/Type.pm
    version: v6.0.33
requires:
  Carp: '0'
  Devel::GlobalDestruction: '0'
  Encode: '0'
  JSON::MaybeXS: '1.004000'
  Math::BigFloat: '0'
  Math::BigInt: '0'
  XSLoader: '0'
  constant: '0'
  namespace::clean: '0'
  overload: '0'
  parent: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/jddurand/c-marpaESLIFPerl/issues
  homepage: https://metacpan.org/release/MarpaX-ESLIF
  repository: git://github.com/jddurand/c-marpaESLIFPerl.git
version: 6.0.33
x_authority: cpan:JDDPAUSE
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
