name: Unix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macos-latest]
        include:
          - os: ubuntu-latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1

    - name: Install perl's File::HomeDir
      run: cpanm -n File::HomeDir

    - name: Print home as per perl
      run: perl -MFile::HomeDir -e 'print "Home as per File::HomeDir is " . File::HomeDir->my_home . "\n";'

    - name: Create ~/.pause
      run: perl -MFile::HomeDir -e 'open(my $fd, ">", File::Spec->catfile(File::HomeDir->my_home, ".pause")); print $fd "JDDPAUSE\nWellWell\n"; close($fd) || warn $!;'

    - name: Verify ~/.pause
      run: perl -MFile::HomeDir -e 'open(my $fd, "<", File::Spec->catfile(File::HomeDir->my_home, ".pause")); my $content = do { local $/; <$fd> }; print $content; close($fd) || warn $!;'

    - name: Configure
      run: cmake -S . -B ../build_folder -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Unix Makefiles" -DINSTALL_DEPENDENCIES=ON

    - name: Build
      run: cmake --build ../build_folder

    - name: Package
      run: cmake --build ../build_folder --target marpaESLIFPerlPackage

    - name: Test
      run: cmake --build ../build_folder --target marpaESLIFPerlTest

    - name: Look for dumps
      run: |
        find ../build_folder -name "hs_err*log" -print -exec cat {} \;
        find ../build_folder -name "core*" -print -exec sh -c 'gdb -c "{}" $(gdb -c "{}" -batch | grep -i "Core was generated by" | perl -ne "/\`([ a-zA-Z0-9_\/-]+)/ && print \"\$1\\n\"") -batch -ex "set pagination 0" -ex "thread apply all bt"' -- {} \;
