name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        cmake_generator: ["Visual Studio 17 2022"]
        cmake_generator_platform: ["Win32","x64"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msbuild@v1.3.1

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        distribution: strawberry

    - name: Install perl's File::HomeDir
      run: cpanm -n File::HomeDir

    - name: Get HomeDir as per perl
      run: perl -MFile::HomeDir -e 'print "Home as per File::HomeDir : " . File::HomeDir->my_home . "\n";'
      id: homedir

    - name: Set PAUSE identity
      shell: cmd
      run: |
        echo user JDDPAUSE > ${{ steps.homedir.outputs.stdout }}
        echo password WellWellComeOn >> ${{ steps.homedir.outputs.stdout }}

    - name: Configure
      run: cmake -S . -B ../build_folder -G "${{matrix.cmake_generator}}" -A "${{matrix.cmake_generator_platform}}" -DINSTALL_DEPENDENCIES=ON

    - name: Build
      run: cmake --build ../build_folder --config ${{env.BUILD_TYPE}}

    - name: Package
      run: cmake --build ../build_folder --target marpaESLIFPerlPackage

    - name: Test
      run: cmake --build ../build_folder --target marpaESLIFPerlTest
