#
# We explicitely use -G "NMake Makefiles" because MSBuild does not like custom commands
# that outputs the word "error". They do NOT fail, but by design MSBuild does not like that...
#
name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        arch: [x86,x64]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{matrix.arch}}

    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        distribution: strawberry

    - name: Print perl configuration
      run: perl -e "use Config qw/myconfig/; print myconfig;"

    - name: Install perl's File::HomeDir
      run: cpanm -n File::HomeDir

    - name: Initialize ~/.pause
      run: perl etc/init_pause.pl JDDPAUSE

    - name: Configure
      run: cmake -S . -B ../build_folder -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DINSTALL_DEPENDENCIES=ON

    - name: Build
      run: cmake --build ../build_folder

    - name: Package
      run: cmake --build ../build_folder

    - name: Test
      run: cmake --build ../build_folder
